services:
  rewards-vpn:
    build: # Build the image using the Dockerfile in the current directory.
      context: .
      dockerfile: Dockerfile
    container_name: rewards_vpn
    network_mode: service:wireguard
    shm_size: 4gb
    depends_on:
      - wireguard
    volumes:
     - ./accounts.json:/app/accounts.json
    restart: unless-stopped

  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ./wg0.conf:/config/wg0.conf
    healthcheck:
      test: [ "CMD", "ping", "-c", "1", "google.com" ]
      retries: 3
      timeout: 5s
    restart: unless-stopped