using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Threading;

namespace MicrosoftRewardsFarmerUI {
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window {

        private Process FarmerProcess = new Process();

        public MainWindow() {
            InitializeComponent();

            //TODO: Get amount of accounts from accounts.json
            AccountComboBox.ItemsSource = new List<int> { 1, 2, 3, 4, 5, 6, 7, 8, 9};
        }

        private void NumericOnly(object sender, TextChangedEventArgs e) {
            string res = string.Empty;

            foreach (char c in ((TextBox)sender).Text) { 
                if (char.IsDigit(c)) {
                    res += c;
                }
            }
            ((TextBox)sender).Text = res;
        }

        private void SubmitButton_Click(object sender, RoutedEventArgs e) {
            FarmerProcess = new Process {
                StartInfo = new ProcessStartInfo {
                    FileName = "python.exe",
                    Arguments = string.Format("-u \"{0}\" \"desktop={1}\" \"mobile={2}\" \"promos={3}\" \"head={4}\" \"email={5}\" \"pwd={6}\"", @"C:\Users\micha\source\repos\MicrosoftRewardsFarmerUI\msr\ms_rewards_farmer.py", "1", "0", "False", "True", "sample@email.com", "password123"),
                    UseShellExecute = false, // Do not use OS shell
                    CreateNoWindow = true, // We don't need new window
                    RedirectStandardOutput = true, // Any output, generated by application will be redirected back
                    RedirectStandardError = true // Any error in standard output will be redirected back (for example exceptions)
                }
            };
            string test = OutputBlock.Text + "test";
            FarmerProcess.OutputDataReceived += DataReceivedEventHandler;
            //FarmerProcess.ErrorDataReceived += (sender, args) => { MessageBox.Show(args.Data + Environment.NewLine); };

            FarmerProcess.Start();
            FarmerProcess.BeginOutputReadLine();
            //FarmerProcess.BeginErrorReadLine();
        }

        private void DataReceivedEventHandler(object sender, DataReceivedEventArgs e) {
            Dispatcher.Invoke(() => { 
                OutputBlock.Text += e.Data + Environment.NewLine; 
            });
        }

        private void KillButton_Click(object sender, RoutedEventArgs e) {
            FarmerProcess.Kill();
            MessageBox.Show("MS Farmer stopped!");
        }

        private void Level1Button_Click(object sender, RoutedEventArgs e) {
            DesktopTextBox.Text = "11";
            MobileTextBox.Text = "0";
            PromosCheckBox.IsChecked = false;
            HeadCheckBox.IsChecked = false;
        }

        private void Level2Button_Click(object sender, RoutedEventArgs e) {
            DesktopTextBox.Text = "30";
            MobileTextBox.Text = "20";
            PromosCheckBox.IsChecked = true;
            HeadCheckBox.IsChecked = false;
        }
    }
}
