using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Threading;

namespace MicrosoftRewardsFarmerUI {
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window {

        private Process FarmerProcess = new Process();
        private List<Account> Accounts;

        public MainWindow() {
            InitializeComponent();
            RefreshAccounts();
        }

        private void RefreshAccounts() {
            Accounts = JsonConvert.DeserializeObject<List<Account>>(File.ReadAllText(@".\data\accounts.json"));
            AccountComboBox.Items.Clear();
            AccountComboBox.Items.Add("New Account...");

            foreach (var account in Accounts) {
                AccountComboBox.Items.Add(account.Username);
            }
            AccountComboBox.SelectedIndex = 1;
        }

        private void NumericOnly(object sender, TextChangedEventArgs e) {
            string res = string.Empty;

            foreach (char c in ((TextBox)sender).Text) {
                if (char.IsDigit(c)) {
                    res += c;
                }
            }
            ((TextBox)sender).Text = res;
        }

        private void SubmitButton_Click(object sender, RoutedEventArgs e) {
            FarmerProcess = new Process {
                StartInfo = new ProcessStartInfo {
                    FileName = "python.exe",
                    Arguments = string.Format("-u \"{0}\" \"desktop={1}\" \"mobile={2}\" \"promos={3}\" \"head={4}\" \"email={5}\" \"pwd={6}\"",
                                                @".\data\ms_rewards_farmer.py", DesktopTextBox.Text, MobileTextBox.Text, PromosCheckBox.IsChecked, HeadCheckBox.IsChecked, EmailTextBox.Text, PasswordTextBox.Password),
                    UseShellExecute = false, // Do not use OS shell
                    CreateNoWindow = true, // We don't need new window
                    RedirectStandardOutput = true, // Any output, generated by application will be redirected back
                    RedirectStandardError = true // Any error in standard output will be redirected back (for example exceptions)
                }
            };
            string test = OutputBlock.Text + "test";
            FarmerProcess.OutputDataReceived += DataReceivedEventHandler;
            //FarmerProcess.ErrorDataReceived += (sender, args) => { MessageBox.Show(args.Data + Environment.NewLine); };

            FarmerProcess.Start();
            FarmerProcess.BeginOutputReadLine();
            //FarmerProcess.BeginErrorReadLine();
        }

        private void DataReceivedEventHandler(object sender, DataReceivedEventArgs e) {
            Dispatcher.Invoke(() => {
                OutputBlock.Text += e.Data + Environment.NewLine;
            });
        }

        private void KillButton_Click(object sender, RoutedEventArgs e) {
            FarmerProcess.Kill();
            OutputBlock.Text += "\n---------------------------------------\n         Farmer Process Killed\n---------------------------------------\n";
        }

        private void Level1Button_Click(object sender, RoutedEventArgs e) {
            DesktopTextBox.Text = "11";
            MobileTextBox.Text = "0";
            PromosCheckBox.IsChecked = false;
            HeadCheckBox.IsChecked = false;
        }

        private void Level2Button_Click(object sender, RoutedEventArgs e) {
            DesktopTextBox.Text = "30";
            MobileTextBox.Text = "20";
            PromosCheckBox.IsChecked = true;
            HeadCheckBox.IsChecked = false;
        }

        private void AccountComboBox_DropDownOpened(object sender, EventArgs e) {
            RefreshAccounts();
        }

        private void AccountComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e) {
            if (AccountComboBox.SelectedIndex == 0) {
                EmailTextBox.Text = "";
                PasswordTextBox.Password = "";
            } else {
                try {
                    EmailTextBox.Text = Accounts[AccountComboBox.SelectedIndex - 1].Username;
                    PasswordTextBox.Password = Accounts[AccountComboBox.SelectedIndex - 1].Password;
                } catch (Exception) {
                    // Do nothing
                }
            }
        }

        private void SaveButton_Click(object sender, RoutedEventArgs e) {
            //Save Account to accounts.json
            if (AccountComboBox.SelectedIndex == 0) {
                // New Account
                Accounts.Add(new Account(EmailTextBox.Text, PasswordTextBox.Password));
            } else {
                // Existing Account
                Accounts[AccountComboBox.SelectedIndex - 1].Username = EmailTextBox.Text;
                Accounts[AccountComboBox.SelectedIndex - 1].Password = PasswordTextBox.Password;
            }
            string json = JsonConvert.SerializeObject(Accounts, Formatting.Indented);
            File.WriteAllText(@".\data\accounts.json", json);
            RefreshAccounts();
        }

        private void DeleteButton_Click(object sender, RoutedEventArgs e) {
            //Delete Account from accounts.json
            if (AccountComboBox.SelectedIndex != 0) {
                Accounts.RemoveAt(AccountComboBox.SelectedIndex - 1);
                string json = JsonConvert.SerializeObject(Accounts, Formatting.Indented);
                File.WriteAllText(@".\data\accounts.json", json);
                RefreshAccounts();
            }
        }

        private void ClearButton_Click(object sender, RoutedEventArgs e) {
            OutputBlock.Text = string.Empty;
        }
    }
}
