using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Threading;

namespace MicrosoftRewardsFarmerUI {
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window {

        private Process InstallProcess;
        private Process FarmerProcess;
        private List<Account> Accounts;

        public MainWindow() {
            InitializeComponent();
            RefreshAccounts();
        }

        private void RefreshAccounts() {
            Accounts = JsonConvert.DeserializeObject<List<Account>>(File.ReadAllText(@".\data\accounts.json"));
            AccountComboBox.Items.Clear();
            AccountComboBox.Items.Add("New Account...");

            foreach (var account in Accounts) {
                AccountComboBox.Items.Add(account.username);
            }
            AccountComboBox.SelectedIndex = 1;

            //Write new account to accounts.json
            string json = JsonConvert.SerializeObject(Accounts, Formatting.Indented);
            File.WriteAllText(@".\data\accounts.json", json);
        }

        private void NumericOnly(object sender, TextChangedEventArgs e) {
            string res = string.Empty;

            foreach (char c in ((TextBox)sender).Text) {
                if (char.IsDigit(c)) {
                    res += c;
                }
            }
            ((TextBox)sender).Text = res;
        }

        private void SubmitButton_Click(object sender, RoutedEventArgs e) {
            //Running Farmer
            FarmerProcess = new Process {
                StartInfo = new ProcessStartInfo {
                    FileName = "python.exe",
                    Arguments = string.Format("-u \"{0}\"{1}{2}{3}{4}", 
                                                @".\data\main.py", (bool)HeadCheckBox.IsChecked ? " -v" : "", LanguageTextBox.Text.Length > 0 ? " -l " + LanguageTextBox.Text : "", 
                                                GeolocationTextBox.Text.Length > 0 ? " -g " + GeolocationTextBox.Text : "", ProxyTextBox.Text.Length > 0 ? " -p " + ProxyTextBox.Text : ""),
                    UseShellExecute = false, // Do not use OS shell
                    CreateNoWindow = true, // We don't need new window
                    RedirectStandardOutput = true, // Any output, generated by application will be redirected back
                    RedirectStandardError = true // Any error in standard output will be redirected back (for example exceptions)
                }
            };
            FarmerProcess.OutputDataReceived += DataReceivedEventHandler;
            FarmerProcess.ErrorDataReceived += DataReceivedEventHandler;

            FarmerProcess.Start();
            FarmerProcess.BeginOutputReadLine();
            FarmerProcess.BeginErrorReadLine();

            //Wait for python script to finish async and send output to OutputBlock
            FarmerProcess.WaitForExitAsync().ContinueWith(task => {
                Dispatcher.Invoke(() => {
                    OutputBlock.Text += "\n---------------------------------------\n         Farmer Finished\n---------------------------------------\n";
                });
            });
        }

        private void DataReceivedEventHandler(object sender, DataReceivedEventArgs e) {
            Dispatcher.Invoke(() => {
                OutputBlock.Text += e.Data + Environment.NewLine;
            });
        }

        private void KillButton_Click(object sender, RoutedEventArgs e) {
            InstallProcess?.Kill();
            FarmerProcess?.Kill();
            OutputBlock.Text += "\n---------------------------------------\n         Farmer Process Killed\n---------------------------------------\n";
        }

        private void AccountComboBox_DropDownOpened(object sender, EventArgs e) {
            RefreshAccounts();
        }

        private void AccountComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e) {
            if (AccountComboBox.SelectedIndex == 0) {
                EmailTextBox.Text = "";
                PasswordTextBox.Password = "";
            } else {
                try {
                    EmailTextBox.Text = Accounts[AccountComboBox.SelectedIndex - 1].username;
                    PasswordTextBox.Password = Accounts[AccountComboBox.SelectedIndex - 1].password;
                } catch (Exception) {
                    // Do nothing
                }
            }
        }

        private void SaveButton_Click(object sender, RoutedEventArgs e) {
            //Save Account to accounts.json
            if (AccountComboBox.SelectedIndex == 0) {
                // New Account
                Accounts.Add(new Account(EmailTextBox.Text, PasswordTextBox.Password));
            } else {
                // Existing Account
                Accounts[AccountComboBox.SelectedIndex - 1].username = EmailTextBox.Text;
                Accounts[AccountComboBox.SelectedIndex - 1].password = PasswordTextBox.Password;
            }
            string json = JsonConvert.SerializeObject(Accounts, Formatting.Indented);
            File.WriteAllText(@".\data\accounts.json", json);
            RefreshAccounts();
        }

        private void DeleteButton_Click(object sender, RoutedEventArgs e) {
            //Delete Account from accounts.json
            if (AccountComboBox.SelectedIndex != 0) {
                Accounts.RemoveAt(AccountComboBox.SelectedIndex - 1);
                string json = JsonConvert.SerializeObject(Accounts, Formatting.Indented);
                File.WriteAllText(@".\data\accounts.json", json);
                RefreshAccounts();
            }
        }

        private void ClearButton_Click(object sender, RoutedEventArgs e) {
            OutputBlock.Text = string.Empty;
        }

        private void InstallButton_Click(object sender, RoutedEventArgs e) {
            //Installing requirements
            InstallProcess = new Process {
                StartInfo = new ProcessStartInfo {
                    FileName = "pip.exe",
                    Arguments = string.Format("install -r {0}", ".\\data\\requirements.txt"),
                    UseShellExecute = false, // Do not use OS shell
                    CreateNoWindow = true, // We don't need new window
                    RedirectStandardOutput = true, // Any output, generated by application will be redirected back
                    RedirectStandardError = true // Any error in standard output will be redirected back (for example exceptions)
                }
            };
            InstallProcess.OutputDataReceived += DataReceivedEventHandler;
            InstallProcess.ErrorDataReceived += DataReceivedEventHandler;

            InstallProcess.Start();
            InstallProcess.BeginOutputReadLine();
            InstallProcess.BeginErrorReadLine();

            //Wait for pip install to finish async and send output to OutputBlock
            InstallProcess.WaitForExitAsync().ContinueWith(task => {
                Dispatcher.Invoke(() => {
                    OutputBlock.Text += "\n---------------------------------------\n         Install Finished\n---------------------------------------\n";
                });
            });
        }

        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e) {
            InstallProcess?.Kill();
            FarmerProcess?.Kill();
        }
    }
}
